jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Get latest Docker image
      run: docker pull pi4j/pi4j-builder:1.4
    - continue-on-error: true
      name: Cross-compile in Docker
      run: docker run --user "$(id -u):$(id -g)" --rm --volume $(pwd):/build pi4j/pi4j-builder:1.4
    - continue-on-error: true
      name: Make staging directory
      run: mkdir staging
    - continue-on-error: true
      name: Copy distribution to staging
      run: 'cp -r pi4j-distribution/target/*.deb staging

        cp -r pi4j-distribution/target/*.zip staging

        '
    - continue-on-error: true
      name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: pi4j-v1-dist
        path: staging
name: crosscompiling
on:
  repository_dispatch:
    types: trigger-ga___crosscompiling.yml
